project_id = "lyyhynjlgebsrdrmnjhk"

[functions.generate-description]
verify_jwt = false

[functions.generate-seo]
verify_jwt = false

[functions.generate-category-image]
verify_jwt = false

[functions.upload-article-images]
verify_jwt = false